out_dir: results
metric_best: accuracy
wandb:
  use: False
  project: Cora
dataset:
  format: PyG
  name: Cora
  task: node
  task_type: classification
  transductive: True
  split_mode: random
  split: [0.8, 0.1, 0.1]
  node_encoder: True
  node_encoder_name: LapPE
#   node_encoder_num_types: 28
  node_encoder_bn: False
  edge_encoder: False
  edge_encoder_name: DummyEdge
#   edge_encoder_num_types: 4
  edge_encoder_bn: False
train:
  mode: inference-only
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: cross_entropy
  edge_decoding: dot
#   graph_pooling: add
gnn:
  head: node
  layers_pre_mp: 0
  layers_post_mp: 3  # Not used when `gnn.head: san_graph`
  dim_inner: 64  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: gelu
  dropout: 0.2
  agg: mean
pretrained:
  dir: results/cora-GPS
  reset_prediction_head: False
